### ISSUE TITLE
Errors in current build

### ISSUE THREAD

**Issue by Joopz0r** [Joopz0r/Survival-Co-Op#12]
[ W VScript              ]: PrecacheResource    must be passed a valid precache context!
[   Developer            ]: ...ta_addons\horde_git\scripts\vscripts\addon_game_mode.lua:394: attempt to index local 'containedItem' (a nil value)
[   Developer            ]: stack traceback:
[   Developer            ]:     ...ta_addons\horde_git\scripts\vscripts\addon_game_mode.lua:394: in function '_ThinkLootExpiry'
[   Developer            ]:     ...ta_addons\horde_git\scripts\vscripts\addon_game_mode.lua:235: in function <...ta_addons\horde_git\scripts\vscripts\addon_game_mode.lua:231>
[ W VScript              ]: Script Runtime Error: ...ta_addons\horde_git\scripts\vscripts\addon_game_mode.lua:394: attempt to index local 'containedItem' (a nil value)
[ W VScript              ]: stack traceback:
[ W VScript              ]:     ...ta_addons\horde_git\scripts\vscripts\addon_game_mode.lua:394: in function '_ThinkLootExpiry'
[ W VScript              ]:     ...ta_addons\horde_git\scripts\vscripts\addon_game_mode.lua:235: in function <...ta_addons\horde_git\scripts\vscripts\addon_game_mode.lua:231>
[ W VScript              ]: PrecacheResource    must be passed a valid precache context!

**Comment by diegogmx** [comment]
fixed in 59b83e249a
